### ISSUE TITLE
can´t execute main.py 

### ISSUE THREAD

**Issue by RustyGoatOC** [OlympicCode/vHackOSBot-Python#12]
when i execute it then it comes to this:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    ut = Utils()
  File "/home/termux/vHackOSBot-Python/utils.py", line 152, in __init__
    self.generateConfiguration(uID="", accessToken="")
  File "/home/termux/vHackOSBot-Python/utils.py", line 328, in generateConfiguration
    self.accessToken = str(parseJson["accesstoken"])
KeyError: 'accesstoken'

**Comment by dgateles** [comment]
Can you provide a example for config.yml edited?

**Comment by siiiik** [comment]
![capture888](https://user-images.githubusercontent.com/37489365/38779563-0b39ead4-40c2-11e8-9d3f-4ec47000b922.PNG)

**Comment by vHackUser** [comment]
just to add if op hasn't resolved it, try removing the files and downloading another copy - worked for multiple people. you may also have a different version of the bot because viewing the latest code, line 17 
 in main.py is blank and ut = Utils() is on line 19. 🤔

**Comment by vHackUser** [comment]
1. Delete the bot files you downloaded
2. Download them again
3. Change config and re-run

**Comment by RustyGoatOC** [comment]
does not work still do i have to delete this part at username and password " <- Your Username Account"
and also do i hve to install the Requirements manual when yes how ?

**Comment by Suburbanno** [comment]
@RustyGoatOC  please edit config.yml with your credentials.

username: nickname123 # <- Your Username Account
password: 321nickname # <- Tour Password Account

pip install -r requirements.txt

python main.py

**Comment by RustyGoatOC** [comment]
i don´t know what i do wrong but when i do "pip install -r requirements.txt"

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by Suburbanno** [comment]
@RustyGoatOC try this
pip install --upgrade pip

pip install -r requirements.txt

**Comment by RustyGoatOC** [comment]
when i do "pip install --upgrade pip"

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by Suburbanno** [comment]
i don't know what the problem is, try this https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

**Comment by RustyGoatOC** [comment]
so i dont know i´ve done this know like deinstalled and installed again and checked also the version but still same error i dont know if this help but i have ubuntu 17.10 and Phython 3

**Comment by RustyGoatOC** [comment]
But one question do i have to run the "pip install --upgrade pip" and "pip install -r requirements.txt" on the "vHackOSBot-Python"  directory or in  the main terminal

**Comment by RustyGoatOC** [comment]
and now i can run the requirements.txt but then there comes this:

Collecting requests==2.14.2 (from -r requirements.txt (line 1))
  Using cached requests-2.14.2-py2.py3-none-any.whl
Collecting ruamel.yaml==0.15.35 (from -r requirements.txt (line 2))
  Using cached ruamel.yaml-0.15.35-cp36-cp36m-manylinux1_x86_64.whl
Collecting coloredlogs==9.0 (from -r requirements.txt (line 3))
  Using cached coloredlogs-9.0-py2.py3-none-any.whl
Collecting terminaltables==3.1.0 (from -r requirements.txt (line 4))
Collecting humanfriendly>=4.7 (from coloredlogs==9.0->-r requirements.txt (line 3))
  Using cached humanfriendly-4.10-py2.py3-none-any.whl
launchpadlib 1.10.5 requires testresources, which is not installed.
Installing collected packages: requests, ruamel.yaml, humanfriendly, coloredlogs, terminaltables
  Found existing installation: requests 2.18.1
    Uninstalling requests-2.18.1:

and this line is red marked: "launchpadlib 1.10.5 requires testresources, which is not installed."

**Comment by RustyGoatOC** [comment]
yeah i installed now my vm completly new

**Comment by RustyGoatOC** [comment]
did u have done any steps before you have installed this on your machine

**Comment by Suburbanno** [comment]
nop

**Comment by Suburbanno** [comment]
use java bot

**Comment by dgateles** [comment]
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    main = run(ut)
  File "main.py", line 15, in __init__
    network = Network(ut)
  File "C:\Users\dgateles\Downloads\vHackOSBot-Python-master\network.py", line 16, in __init__
    self.createMalwareKit()
  File "C:\Users\dgateles\Downloads\vHackOSBot-Python-master\network.py", line 130, in createMalwareKit
    if int(malware["tasksCount"]) != 1:
KeyError: 'tasksCount'
