### ISSUE TITLE
new feature suggestion

### ISSUE THREAD

**Issue by vHackUser** [OlympicCode/vHackOSBot-Python#13]
add self.ChangeLog(PlayerBruteIP) to line 120 of network.py to clear the logs after checking for money and finding an empty bank account - tried this but it caused an error: `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
any possible fixes if I were to modify this section of code?

be aware i have no idea what i'm doing, i just know that this works for a few times before breaking

**Comment by vBlackOut** [comment]
please connect on discord and say your request
