### ISSUE TITLE
Cant start the program

### ISSUE THREAD

**Issue by Slon4564556** [OlympicCode/vHackOSBot-Python#15]
So i tried to execute this program but I have an error
![capturefqzfzfq](https://user-images.githubusercontent.com/38539735/39012188-00a8e9c6-4414-11e8-870e-a83ba2807e52.PNG)

I hope you can help me,

**Comment by vHackUser** [comment]
Have you:
- Entered your username and password into config.yml
- Tried reinstalling the bot then editing the config.yml

If so,
- Paste your config.yml here without username & password
