### ISSUE TITLE
Nothing happens when i start 

### ISSUE THREAD

**Issue by jawiegehts** [OlympicCode/vHackOSBot-Python#6]
Installed all the requirements, filled in all the credentials and tried to run in cmd (windows) and in the python shell .. nothing happens
[https://i.imgur.com/Mi0ceXN.png](url)

**Comment by checkium** [comment]
The python bot is currently outdated and will not work

**Comment by jawiegehts** [comment]
oh x)

**Comment by checkium** [comment]
For now you can use the java bot, join [our discord](https://discord.gg/52MtBDp) if you need any help :)

**Comment by jawiegehts** [comment]
awesome alright thx =)
